---
require:
- rubocop-rspec
AllCops:
  NewCops: disable
  DisplayCopNames: true
  TargetRubyVersion: '2.5'
  Include:
  - "**/*.rb"
  Exclude:
  - bin/*
  - ".vendor/**/*"
  - "**/Gemfile"
  - "**/Rakefile"
  - pkg/**/*
  - spec/fixtures/**/*
  - vendor/**/*
  - "**/Puppetfile"
  - "**/Vagrantfile"
  - "**/Guardfile"
  - "**/Dockerfile"
  - spec/**/*
# RSpec/BeforeAfterAll:
#   Description: Beware of using after(:all) as it may cause state to leak between tests.
#     A necessary evil in acceptance testing.
#   Exclude:
#   - spec/acceptance/**/*.rb
# RSpec/HookArgument:
#   Description: Prefer explicit :each argument, matching existing module's style
#   EnforcedStyle: each
# RSpec/DescribeSymbol:
#   Exclude:
#   - spec/unit/facter/**/*.rb
# Style/BlockDelimiters:
#   Description: Prefer braces for chaining. Mostly an aesthetical choice. Better to
#     be consistent then.
#   EnforcedStyle: braces_for_chaining
# Style/ClassAndModuleChildren:
#   Description: Compact style reduces the required amount of indentation.
#   EnforcedStyle: compact
Style/EmptyElse:
  Description: Enforce against empty else clauses, but allow `nil` for clarity.
  EnforcedStyle: empty
# Style/FormatString:
#   Description: Following the main puppet project's style, prefer the % format format.
#   EnforcedStyle: percent
# Style/FormatStringToken:
#   Description: Following the main puppet project's style, prefer the simpler template
#     tokens over annotated ones.
#   EnforcedStyle: template
# Style/Lambda:
#   Description: Prefer the keyword for easier discoverability.
#   EnforcedStyle: literal
# Style/RegexpLiteral:
#   Description: Community preference. See https://github.com/voxpupuli/modulesync_config/issues/168
#   EnforcedStyle: percent_r
# Style/TernaryParentheses:
#   Description: Checks for use of parentheses around ternary conditions. Enforce parentheses
#     on complex expressions for better readability, but seriously consider breaking
#     it up.
#   EnforcedStyle: require_parentheses_when_complex
# Style/TrailingCommaInArguments:
#   Description: Prefer always trailing comma on multiline argument lists. This makes
#     diffs, and re-ordering nicer.
#   EnforcedStyleForMultiline: comma
# Style/TrailingCommaInArrayLiteral:
#   Description: Prefer always trailing comma on multiline literals. This makes diffs,
#     and re-ordering nicer.
#   EnforcedStyleForMultiline: comma
# Style/SymbolArray:
#   Description: Using percent style obscures symbolic intent of array's contents.
#   EnforcedStyle: brackets
# RSpec/MessageSpies:
#   EnforcedStyle: receive
Style/Documentation:
  Exclude:
  - lib/puppet/parser/functions/**/*
  - spec/**/*
# Style/WordArray:
#   EnforcedStyle: brackets
# Style/CollectionMethods:
#   Enabled: true
# Style/MethodCalledOnDoEndBlock:
#   Enabled: true
# Style/StringMethods:
#   Enabled: true
Bundler/InsecureProtocolSource:
  Enabled: true
Gemspec/DuplicatedAssignment:
  Enabled: true
Gemspec/OrderedDependencies:
  Enabled: true
Gemspec/RequiredRubyVersion:
  Enabled: true
Gemspec/RubyVersionGlobalsUsage:
  Enabled: true
Layout/ArgumentAlignment:
  Enabled: true
Layout/BeginEndAlignment:
  Enabled: true
Layout/ClosingHeredocIndentation:
  Enabled: true
Layout/EmptyComment:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/EmptyLinesAroundArguments:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EndOfLine:
  Enabled: true
Layout/FirstArgumentIndentation:
  Enabled: true
Layout/HashAlignment:
  Enabled: true
Layout/HeredocIndentation:
  Enabled: true
Layout/LeadingEmptyLines:
  Enabled: true
Layout/LineLength:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
Layout/SpaceInsideReferenceBrackets:
  Enabled: true
Lint/BigDecimalNew:
  Enabled: true
Lint/BooleanSymbol:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DisjunctiveAssignmentInConstructor:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/ErbNewArguments:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/HashCompareByIdentity:
  Enabled: true
Lint/IdentityComparison:
  Enabled: true
Lint/InterpolationCheck:
  Enabled: true
Lint/MissingCopEnableDirective:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/NestedPercentLiteral:
  Enabled: true
Lint/NonDeterministicRequireOrder:
  Enabled: true
Lint/OrderedMagicComments:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/RedundantCopEnableDirective:
  Enabled: true
Lint/RedundantRequireStatement:
  Enabled: true
Lint/RedundantSafeNavigation:
  Enabled: true
Lint/RedundantWithIndex:
  Enabled: true
Lint/RedundantWithObject:
  Enabled: true
Lint/RegexpAsCondition:
  Enabled: true
Lint/ReturnInVoidContext:
  Enabled: true
Lint/SafeNavigationConsistency:
  Enabled: true
Lint/SafeNavigationWithEmpty:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/SendWithMixinArgument:
  Enabled: true
Lint/ShadowedArgument:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/ToJSON:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UriEscapeUnescape:
  Enabled: true
Lint/UriRegexp:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Lint/UselessTimes:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: true
Metrics/ClassLength:
  Max: 140
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/MethodLength:
  CountComments: false
  Max: 200
Metrics/ModuleLength:
  Enabled: true
Metrics/ParameterLists:
  Enabled: true
Metrics/PerceivedComplexity:
  Enabled: false
Migration/DepartmentName:
  Enabled: true
Naming/AccessorMethodName:
  Enabled: true
Naming/BlockParameterName:
  Enabled: true
Naming/HeredocDelimiterCase:
  Enabled: true
Naming/HeredocDelimiterNaming:
  Enabled: true
Naming/MemoizedInstanceVariableName:
  Enabled: true
Naming/MethodParameterName:
  Enabled: true
Naming/RescuedExceptionsVariableName:
  Enabled: true
Naming/VariableNumber:
  Enabled: true
RSpec/Be:
  Enabled: true
RSpec/ContextMethod:
  Enabled: true
RSpec/ContextWording:
  Enabled: true
RSpec/DescribeClass:
  Enabled: true
RSpec/EmptyHook:
  Enabled: true
RSpec/EmptyLineAfterExample:
  Enabled: true
RSpec/EmptyLineAfterExampleGroup:
  Enabled: true
RSpec/EmptyLineAfterHook:
  Enabled: true
RSpec/ExampleLength:
  Enabled: true
RSpec/ExampleWithoutDescription:
  Enabled: true
RSpec/ExpectChange:
  Enabled: true
RSpec/ExpectInHook:
  Enabled: true
RSpec/HooksBeforeExamples:
  Enabled: true
RSpec/ImplicitBlockExpectation:
  Enabled: true
RSpec/ImplicitSubject:
  Enabled: true
RSpec/LeakyConstantDeclaration:
  Enabled: true
RSpec/LetBeforeExamples:
  Enabled: true
RSpec/MissingExampleGroupArgument:
  Enabled: true
RSpec/MultipleExpectations:
  Enabled: true
# RSpec/MultipleMemoizedHelpers:
RSpec/MultipleDescribes:
  Enabled: true
RSpec/MultipleSubjects:
  Enabled: true
RSpec/NestedGroups:
  Enabled: true
RSpec/PredicateMatcher:
  Enabled: true
RSpec/ReceiveCounts:
  Enabled: true
RSpec/ReceiveNever:
  Enabled: true
RSpec/RepeatedExampleGroupBody:
  Enabled: true
RSpec/RepeatedExampleGroupDescription:
  Enabled: true
# RSpec/RepeatedIncludeExample:
RSpec/RepeatedExample:
  Enabled: true
RSpec/ReturnFromStub:
  Enabled: true
RSpec/SharedExamples:
  Enabled: true
# RSpec/StubbedMock:
RSpec/Focus:
  Enabled: true
RSpec/UnspecifiedException:
  Enabled: true
RSpec/VariableDefinition:
  Enabled: true
RSpec/VoidExpect:
  Enabled: true
RSpec/Yield:
  Enabled: true
Security/Open:
  Enabled: true
Style/AccessModifierDeclarations:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/AsciiComments:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: true
Style/ClassEqualityComparison:
  Enabled: true
Style/ColonMethodDefinition:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/CommentedKeyword:
  Enabled: true
Style/Dir:
  Enabled: true
Style/DoubleCopDisableDirective:
  Enabled: true
Style/EmptyBlockParameter:
  Enabled: true
Style/EmptyLambdaParameter:
  Enabled: true
Style/Encoding:
  Enabled: true
Style/EvalWithLocation:
  Enabled: true
Style/ExpandPathArguments:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/FloatDivision:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: true
Style/KeywordParametersOrder:
  Enabled: true
Style/MinMax:
  Enabled: true
Style/MixinUsage:
  Enabled: true
Style/MultilineWhenThen:
  Enabled: true
Style/MultilineIfModifier:
  Enabled: true
Style/NegatedUnless:
  Enabled: true
Style/NumericPredicate:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/OrAssignment:
  Enabled: true
Style/RandomWithOffset:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantBegin:
  Enabled: true
Style/RedundantCondition:
  Enabled: true
Style/RedundantConditional:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true
Style/RedundantSort:
  Enabled: true
Style/RescueStandardError:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Style/StderrPuts:
  Enabled: true
Style/StringConcatenation:
  Enabled: true
Style/Strip:
  Enabled: true
Style/SymbolProc:
  Enabled: true
Style/TrailingBodyOnClass:
  Enabled: true
Style/TrailingBodyOnMethodDefinition:
  Enabled: true
Style/TrailingBodyOnModule:
  Enabled: true
Style/TrailingCommaInHashLiteral:
  Enabled: true
Style/TrailingMethodEndStatement:
  Enabled: true
Style/UnpackFirst:
  Enabled: true
