Metrics/MethodLength:
  CountComments: false
  Max: 150
Layout/LineLength:
  Max: 200
ParameterLists:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/ClassLength:
  Max: 150
AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*.rb'
