sudo: required
services:
- docker
cache:
  bundler: true
  directories:
  - spec/fixtures/artifacts
  - spec/fixtures/modules
  - ".vendor"
language: ruby
git:
  depth: 3
env:
  global:
  - TEST_SUITE=acceptance
  - BUNDLE_PATH=.vendor
  - GRAPHDB_TIMEOUT=200
  - DEBUG=false
  matrix:
  - TEST_SUITE=rspec
  - DISTRO=centos-6-x64
  - DISTRO=centos-7-x64
  - DISTRO=debian-7-x64
  - DISTRO=debian-8-x64
  - DISTRO=ubuntu-server-1204-x64
  - DISTRO=ubuntu-server-1404-x64
script:
- make test-$TEST_SUITE
before_install:
- openssl aes-256-cbc -K $encrypted_c1be2d1aa63f_key -iv $encrypted_c1be2d1aa63f_iv
  -in licenses.tar.enc -out licenses.tar -d
- tar xvf licenses.tar
