 {
   "language": "ruby",
   "sudo": false,
   "before_install": [
     "gem install bundler -v 1.10"
   ],
   "bundler_args": "--without development",
   "script": [
     "bundle exec rake"
   ],
   "rvm": "2.3.1",
   "group": "stable",
   "dist": "precise",
   "os": "linux"
 }
